
; messages (or events) sent from the server to the client
msg
    = msgFree
    \ msgLock
    \ msgInput
    \ msgOutput
    \ msgSuccess
    \ msgFailure
    \ msgClose
    \ msgError;

clientReq =  clientReqFree \ clientReqLock;

msgFree    = [ 0, utxoRef, addr ]
msgLock    = [ 1, utxoRef, addr ]
msgInput   = [ 2, utxoRef, addr, txHash ]; txHash of the tx that spent the utxo
msgOutput  = [ 3, utxoRef, addr ];
msgSuccess = [ 4, id, successData ];
msgFailure = [ 5, id, failureData ];
msgClose   = [ 6 ];
msgError   = [ 7, errorType ];

clientReq
    = clientReqFree
    \ clientReqLock
    \ clientSub
    \ clientUnsub

; messages sent from the client to the server
clientReqFree = [ 0, id, [ + utxoRef ] ];
clientReqLock = [
    1,
    id,
    [ + utxoRef ], ; utxos to lock
    ? uint; (optional) number of required utxos to lock in order to succeed, defaults to `1`
];
clientSub = [ 2, id, eventType, [ * filter ] ];
clientUnsub = [ 3, id, eventType, [ * filter ] ];

eventType = uint .size 1 ; unsigned integer 1 byte
; 0: Free
; 1: Lock
; 2: Input
; 3: Output
; 4: Success
; 5: Failure
; 6: Close
; 7: Error

filter
    = [ 0, addr ]
    \ [ 1, utxoRef ]

failureData
    = [ 0, [* utxoRef] ]; no utxos were freed, sending back utxo requested
    \ [ 1, [* utxoRef] ]; no utxos were locked, sending back utxo requested

successData 
    = [ 0, [+ utxoRef] ]; utxos were freed
    \ [ 1, [+ utxoRef] ]; utxos were locked

errorType = uint .size 1 ; unsigned integer 1 byte
errorType = (
    0 ; not authenticated
    \ 1 ; missing Ip
    \ 2 ; invalid auth token
    \ 3 ; too many requests, rate limited
    \ 4 ; address is not followed
    \ 5 ; utxo not found
    \ 6 ; unkown event to subscribe by address
    \ 7 ; unkown event to subscribe by utxoRef
    \ 8 ; unkown event to un-subscribe by address
    \ 9 ; unkown event to un-subscribe by utxoRef
    \ 10 ; unsub message sent; but no event specified
)

utxoRef = [ hash32, uint ]

txHash = hash32;

id = uint .size 8;

hash32 = bytes .size 32;
addr = bytes; according to the cardano-ledger cddl (babbage)
